API_BASE = "https://script.google.com/macros/s/AKfycbyKtYk4wOSArwD1nx-snr1KNlC_JmZSuKpE57sKTCbPSnYwX62ii3trXywDHsep6l9O8w/exec"
APP_TITLE = "Dessa – Asisten Pengingat"

#AKfycbxbhRpbjADnhEK5Nhnm7imEbuWT9AVs9jL8Fme18Ov7xV8pQhsO8N92b9UtS3nFiyBRRQ, AKfycbxWlt8-Z5jm8bG1HZZcZOnlK3gDZjQ5TCqR076KGAN7D5S6KAYs4zA7FCcuLQX9fGtWwA